name: NTT News Bot

env:
  GMAIL_USER: ${{ secrets.GMAIL_USER }}
  GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
  TO_EMAIL: ${{ secrets.TO_EMAIL }}

on:
  schedule:
    - cron: '0 2 * * *'  # 毎日JSTの11時に実行
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 lxml yfinance

      - name: Run script
        run: python ntt_news_scraper.py
        env:
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
